"""API route modules"""

from . import (
    health, games, sports, bug_reports, parlay, auth, analytics, social, websocket, variants, reports, analysis,
    parlay_extended, team_stats, scraper, user, events, billing, webhooks, profile, me, subscription, notifications,
    live_games, parlay_tips, metrics, affiliate, custom_parlay, upset_finder, saved_parlays, promo_codes, parlays_results,
    leaderboards,
    analysis_feed,
    redirects,
    saved_parlay_verification,
    verification_records,
    gorilla_bot,
    meta,
    tools,
    feed,
    system,
    games_public_routes,
)
from .admin import router as admin_router

__all__ = [
    "health", "games", "sports", "bug_reports", "parlay", "auth", "analytics", "social", "websocket", 
    "variants", "reports", "analysis", "parlay_extended", "team_stats", "scraper", "user",
    "events", "admin_router", "billing", "webhooks", "profile", "me", "subscription", "notifications",
    "live_games",
    "parlay_tips",
    "metrics",
    "affiliate",
    "custom_parlay",
    "upset_finder",
    "saved_parlays",
    "saved_parlay_verification",
    "promo_codes",
    "parlays_results",
    "leaderboards",
    "analysis_feed",
    "redirects",
    "verification_records",
    "gorilla_bot",
    "meta",
    "tools",
    "feed",
    "system",
    "games_public_routes",
]
