"""Check what Render deployment information you have and what you need.

This script reads your .env file and shows:
- What API keys you already have
- What you still need to get
- Quick links to get missing keys
"""

import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from app.core.config import settings
except ImportError:
    print("Error: Could not import settings. Make sure you're in the backend directory.")
    sys.exit(1)


def check_env_var(key: str, value: any) -> Tuple[bool, str]:
    """Check if an environment variable is set and not empty."""
    if not value:
        return False, "❌ Missing"
    if isinstance(value, str) and value.strip() == "":
        return False, "❌ Empty"
    if "your_key_here" in str(value).lower() or "your_" in str(value).lower():
        return False, "⚠️  Placeholder"
    # Mask sensitive values
    if len(str(value)) > 20:
        masked = str(value)[:8] + "..." + str(value)[-4:]
    else:
        masked = "***" * 4
    return True, f"✅ Set ({masked})"


def print_section(title: str):
    """Print a section header."""
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")


def print_item(name: str, status: str, notes: str = ""):
    """Print a checklist item."""
    print(f"  {status} {name}")
    if notes:
        print(f"      {notes}")


def main():
    """Main function to check Render setup."""
    print("\n" + "="*60)
    print("  🚀 Render Deployment Setup Checker")
    print("="*60)
    
    # Required variables
    print_section("🔴 REQUIRED VARIABLES")
    
    required_vars = {
        "THE_ODDS_API_KEY": {
            "value": getattr(settings, "the_odds_api_key", None),
            "where": "https://the-odds-api.com - Dashboard → API Keys",
            "notes": "Free tier: 500 requests/month"
        },
        "OPENAI_API_KEY": {
            "value": getattr(settings, "openai_api_key", None),
            "where": "https://platform.openai.com - API Keys section",
            "notes": "Requires payment method"
        },
        "JWT_SECRET": {
            "value": getattr(settings, "jwt_secret", None),
            "where": "Auto-generated by Render (no action needed)",
            "notes": "Render will generate this automatically"
        },
    }
    
    for var_name, info in required_vars.items():
        has_value, status = check_env_var(var_name, info["value"])
        print_item(var_name, status)
        if not has_value or "Placeholder" in status:
            print(f"      📍 Get it from: {info['where']}")
            if "notes" in info:
                print(f"      💡 {info['notes']}")
    
    # URLs (need to be set in Render)
    print_section("🌐 DOMAIN URLs (Set in Render Dashboard)")
    
    url_vars = {
        "FRONTEND_URL": {
            "current": getattr(settings, "frontend_url", "http://localhost:3000"),
            "render_default": "https://parlay-gorilla-frontend.onrender.com",
            "notes": "Your frontend domain or Render default"
        },
        "BACKEND_URL": {
            "current": getattr(settings, "backend_url", "http://localhost:8000"),
            "render_default": "https://parlay-gorilla-backend.onrender.com",
            "notes": "Your backend API domain or Render default"
        },
        "APP_URL": {
            "current": getattr(settings, "app_url", "http://localhost:3000"),
            "render_default": "https://parlay-gorilla-frontend.onrender.com",
            "notes": "Same as FRONTEND_URL"
        },
    }
    
    for var_name, info in url_vars.items():
        current = info["current"]
        if "localhost" in current or "127.0.0.1" in current:
            print_item(var_name, "⚠️  Using localhost (update for Render)")
            print(f"      💡 Render default: {info['render_default']}")
            print(f"      📝 Set this in Render dashboard after deployment")
        else:
            print_item(var_name, f"✅ {current}")
    
    # Optional but recommended
    print_section("🟡 OPTIONAL (But Recommended)")
    
    optional_vars = {
        "RESEND_API_KEY": {
            "value": getattr(settings, "resend_api_key", None),
            "where": "https://resend.com - API Keys",
            "notes": "Enables email verification & password reset"
        },
        "SPORTSRADAR_API_KEY": {
            "value": getattr(settings, "sportsradar_api_key", None),
            "where": "https://developer.sportradar.com",
            "notes": "For live game data, schedules, stats"
        },
        "OPENWEATHER_API_KEY": {
            "value": getattr(settings, "openweather_api_key", None),
            "where": "https://openweathermap.org/api",
            "notes": "For weather data in game analysis"
        },
        "PEXELS_API_KEY": {
            "value": getattr(settings, "pexels_api_key", None),
            "where": "https://www.pexels.com/api",
            "notes": "For team action photos"
        },
    }
    
    for var_name, info in optional_vars.items():
        has_value, status = check_env_var(var_name, info["value"])
        print_item(var_name, status)
        if not has_value or "Placeholder" in status:
            print(f"      📍 Get it from: {info['where']}")
            if "notes" in info:
                print(f"      💡 {info['notes']}")
    
    # Payment providers
    print_section("💳 PAYMENT PROVIDERS (Optional)")
    
    payment_vars = {
        "LEMONSQUEEZY_API_KEY": {
            "value": os.getenv("LEMONSQUEEZY_API_KEY"),
            "where": "https://app.lemonsqueezy.com - Settings → API",
            "notes": "For subscriptions & credit packs"
        },
        "LEMONSQUEEZY_STORE_ID": {
            "value": os.getenv("LEMONSQUEEZY_STORE_ID"),
            "where": "https://app.lemonsqueezy.com - Settings → General",
            "notes": "Your LemonSqueezy store ID"
        },
        "COINBASE_COMMERCE_API_KEY": {
            "value": os.getenv("COINBASE_COMMERCE_API_KEY"),
            "where": "https://commerce.coinbase.com - Settings → API Keys",
            "notes": "For crypto payments"
        },
    }
    
    for var_name, info in payment_vars.items():
        has_value, status = check_env_var(var_name, info["value"])
        print_item(var_name, status)
        if not has_value:
            print(f"      📍 Get it from: {info['where']}")
            if "notes" in info:
                print(f"      💡 {info['notes']}")
    
    # Inscriptions (Solana)
    print_section("⛓️  INSCRIPTIONS WORKER (Optional)")
    
    inscriptions_vars = {
        "SIGNER_PRIVATE_KEY": {
            "value": os.getenv("SIGNER_PRIVATE_KEY"),
            "where": "Generate Solana wallet or use existing",
            "notes": "⚠️  Keep secret! Never commit to git"
        },
        "RPC": {
            "value": os.getenv("RPC"),
            "where": "Helius/QuickNode/Alchemy (or public RPC)",
            "notes": "Solana RPC endpoint URL"
        },
    }
    
    for var_name, info in inscriptions_vars.items():
        has_value, status = check_env_var(var_name, info["value"])
        print_item(var_name, status)
        if not has_value:
            print(f"      📍 Get it from: {info['where']}")
            if "notes" in info:
                print(f"      💡 {info['notes']}")
    
    # Auto-wired by Render
    print_section("✅ AUTO-WIRED BY RENDER (No Action Needed)")
    
    auto_wired = [
        "DATABASE_URL - From PostgreSQL database",
        "REDIS_URL - From Key Value store",
        "JWT_SECRET - Auto-generated",
        "ENVIRONMENT - Set to 'production'",
        "DEBUG - Set to 'false'",
        "USE_SQLITE - Set to 'false'",
        "OPENAI_ENABLED - Set to 'true'",
    ]
    
    for item in auto_wired:
        print(f"  ✅ {item}")
    
    # Summary
    print_section("📊 SUMMARY")
    
    # Count what we have
    all_vars = {**required_vars, **optional_vars, **payment_vars, **inscriptions_vars}
    have_count = sum(1 for v in all_vars.values() if v["value"] and "your_" not in str(v["value"]).lower())
    total_count = len(all_vars)
    
    print(f"  📈 You have {have_count}/{total_count} optional variables set")
    print(f"  ✅ All required variables are ready!")
    print(f"\n  🚀 Next steps:")
    print(f"     1. Decide on your domain URLs (or use Render defaults)")
    print(f"     2. Set up optional services if needed (LemonSqueezy, Coinbase, etc.)")
    print(f"     3. Deploy to Render using render.yaml Blueprint")
    print(f"     4. Copy your .env values to Render dashboard")
    print(f"\n  📖 See RENDER_SETUP_GUIDE.md for detailed instructions")


if __name__ == "__main__":
    main()

