/**
 * Comprehensive team lists for all sports
 * Used for profile setup and team selection
 */

export const ALL_TEAMS: Record<string, string[]> = {
  NFL: [
    "Arizona Cardinals",
    "Atlanta Falcons",
    "Baltimore Ravens",
    "Buffalo Bills",
    "Carolina Panthers",
    "Chicago Bears",
    "Cincinnati Bengals",
    "Cleveland Browns",
    "Dallas Cowboys",
    "Denver Broncos",
    "Detroit Lions",
    "Green Bay Packers",
    "Houston Texans",
    "Indianapolis Colts",
    "Jacksonville Jaguars",
    "Kansas City Chiefs",
    "Las Vegas Raiders",
    "Los Angeles Chargers",
    "Los Angeles Rams",
    "Miami Dolphins",
    "Minnesota Vikings",
    "New England Patriots",
    "New Orleans Saints",
    "New York Giants",
    "New York Jets",
    "Philadelphia Eagles",
    "Pittsburgh Steelers",
    "San Francisco 49ers",
    "Seattle Seahawks",
    "Tampa Bay Buccaneers",
    "Tennessee Titans",
    "Washington Commanders",
  ],
  NBA: [
    "Atlanta Hawks",
    "Boston Celtics",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Cleveland Cavaliers",
    "Dallas Mavericks",
    "Denver Nuggets",
    "Detroit Pistons",
    "Golden State Warriors",
    "Houston Rockets",
    "Indiana Pacers",
    "Los Angeles Clippers",
    "Los Angeles Lakers",
    "Memphis Grizzlies",
    "Miami Heat",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "New Orleans Pelicans",
    "New York Knicks",
    "Oklahoma City Thunder",
    "Orlando Magic",
    "Philadelphia 76ers",
    "Phoenix Suns",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards",
  ],
  NHL: [
    "Anaheim Ducks",
    "Arizona Coyotes",
    "Boston Bruins",
    "Buffalo Sabres",
    "Calgary Flames",
    "Carolina Hurricanes",
    "Chicago Blackhawks",
    "Colorado Avalanche",
    "Columbus Blue Jackets",
    "Dallas Stars",
    "Detroit Red Wings",
    "Edmonton Oilers",
    "Florida Panthers",
    "Los Angeles Kings",
    "Minnesota Wild",
    "Montreal Canadiens",
    "Nashville Predators",
    "New Jersey Devils",
    "New York Islanders",
    "New York Rangers",
    "Ottawa Senators",
    "Philadelphia Flyers",
    "Pittsburgh Penguins",
    "San Jose Sharks",
    "Seattle Kraken",
    "St. Louis Blues",
    "Tampa Bay Lightning",
    "Toronto Maple Leafs",
    "Utah Hockey Club",
    "Vancouver Canucks",
    "Vegas Golden Knights",
    "Washington Capitals",
    "Winnipeg Jets",
  ],
  MLB: [
    "Arizona Diamondbacks",
    "Atlanta Braves",
    "Baltimore Orioles",
    "Boston Red Sox",
    "Chicago Cubs",
    "Chicago White Sox",
    "Cincinnati Reds",
    "Cleveland Guardians",
    "Colorado Rockies",
    "Detroit Tigers",
    "Houston Astros",
    "Kansas City Royals",
    "Los Angeles Angels",
    "Los Angeles Dodgers",
    "Miami Marlins",
    "Milwaukee Brewers",
    "Minnesota Twins",
    "New York Mets",
    "New York Yankees",
    "Oakland Athletics",
    "Philadelphia Phillies",
    "Pittsburgh Pirates",
    "San Diego Padres",
    "San Francisco Giants",
    "Seattle Mariners",
    "St. Louis Cardinals",
    "Tampa Bay Rays",
    "Texas Rangers",
    "Toronto Blue Jays",
    "Washington Nationals",
  ],
  NCAAF: [
    "Alabama",
    "Auburn",
    "Clemson",
    "Florida",
    "Florida State",
    "Georgia",
    "LSU",
    "Miami",
    "Michigan",
    "Michigan State",
    "Notre Dame",
    "Ohio State",
    "Oklahoma",
    "Oregon",
    "Penn State",
    "Tennessee",
    "Texas",
    "Texas A&M",
    "USC",
    "Wisconsin",
    // Add more popular teams
    "Arizona",
    "Arizona State",
    "Arkansas",
    "Baylor",
    "Boise State",
    "BYU",
    "Cincinnati",
    "Colorado",
    "Duke",
    "Georgia Tech",
    "Iowa",
    "Iowa State",
    "Kansas",
    "Kansas State",
    "Kentucky",
    "Louisville",
    "Maryland",
    "Miami (FL)",
    "Mississippi State",
    "Missouri",
    "NC State",
    "Nebraska",
    "North Carolina",
    "Northwestern",
    "Oklahoma State",
    "Ole Miss",
    "Oregon State",
    "Pittsburgh",
    "Purdue",
    "Rutgers",
    "South Carolina",
    "Stanford",
    "Syracuse",
    "TCU",
    "Texas Tech",
    "UCF",
    "UCLA",
    "Utah",
    "Virginia",
    "Virginia Tech",
    "Washington",
    "Washington State",
    "West Virginia",
  ],
  NCAAB: [
    "Alabama",
    "Arizona",
    "Arkansas",
    "Auburn",
    "Baylor",
    "Butler",
    "Cincinnati",
    "Connecticut",
    "Creighton",
    "Duke",
    "Florida",
    "Gonzaga",
    "Houston",
    "Illinois",
    "Indiana",
    "Iowa",
    "Iowa State",
    "Kansas",
    "Kansas State",
    "Kentucky",
    "Louisville",
    "Marquette",
    "Maryland",
    "Memphis",
    "Michigan",
    "Michigan State",
    "North Carolina",
    "Northwestern",
    "Ohio State",
    "Oklahoma",
    "Oregon",
    "Penn State",
    "Purdue",
    "Rutgers",
    "San Diego State",
    "Seton Hall",
    "Syracuse",
    "TCU",
    "Tennessee",
    "Texas",
    "Texas Tech",
    "UCLA",
    "USC",
    "Villanova",
    "Virginia",
    "Wisconsin",
    "Xavier",
  ],
  Soccer: [
    // MLS
    "Atlanta United",
    "Austin FC",
    "Charlotte FC",
    "Chicago Fire",
    "FC Cincinnati",
    "Colorado Rapids",
    "Columbus Crew",
    "DC United",
    "FC Dallas",
    "Houston Dynamo",
    "Inter Miami",
    "LA Galaxy",
    "Los Angeles FC",
    "Minnesota United",
    "CF Montréal",
    "Nashville SC",
    "New England Revolution",
    "New York City FC",
    "New York Red Bulls",
    "Orlando City",
    "Philadelphia Union",
    "Portland Timbers",
    "Real Salt Lake",
    "San Jose Earthquakes",
    "Seattle Sounders",
    "Sporting Kansas City",
    "St. Louis City SC",
    "Toronto FC",
    "Vancouver Whitecaps",
    // EPL
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brentford",
    "Brighton",
    "Burnley",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Liverpool",
    "Luton Town",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Sheffield United",
    "Tottenham",
    "West Ham",
    "Wolves",
    // La Liga
    "Real Madrid",
    "Barcelona",
    "Atletico Madrid",
    "Sevilla",
    "Valencia",
    "Real Sociedad",
    "Villarreal",
    "Athletic Bilbao",
    "Real Betis",
    "Osasuna",
  ],
}




